package app;

/**
 *
 * @author Emiliano Cepeda Villarreal N#20130792
 */
import java.sql.SQLException;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//---------------------------------------------
import java.sql.DriverManager;
import javax.sql.rowset.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class RegistroAutos extends javax.swing.JFrame {

    RowSetFactory factory;
    CachedRowSet rowSet;

    /**
     * Creates new form RegistroAutos
     */
    public RegistroAutos() throws SQLException {
        initComponents();
        jTFID.setVisible(false);
        cargarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFPlacas = new javax.swing.JTextField();
        jTFModelo = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jTFSerie = new javax.swing.JTextField();
        jTFCve = new javax.swing.JTextField();
        jTFID = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jTFContraseña = new javax.swing.JTextField();
        jCBMostrar = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNOMBRE = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Vehicular");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS VEHICULO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PLACAS: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("MODELO: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("MARCA: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("N# SERIE: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CVE VEHICULO: ");

        jTFPlacas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTFCve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jTFContraseña.setToolTipText("CONTRASEÑA");

        jCBMostrar.setText("Clave Seguridad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFSerie)
                            .addComponent(jTFModelo)
                            .addComponent(jTFMarca)
                            .addComponent(jTFCve)
                            .addComponent(jTFPlacas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jCBMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFCve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonLimpiar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBMostrar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTableVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Placas", "Modelo", "Marca", "N#Serie", "CVE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVehiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVehiculo);
        if (jTableVehiculo.getColumnModel().getColumnCount() > 0) {
            jTableVehiculo.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTableVehiculo.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableVehiculo.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CONCESIONARIA DE AUTOMOVILES");

        jTextFieldNOMBRE.setEditable(false);
        jTextFieldNOMBRE.setText(" EMILIANO CEPEDA VILLARREAL N#20130792");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVehiculoMouseClicked

        try {
            int fila = jTableVehiculo.getSelectedRow();
            int id = Integer.parseInt(jTableVehiculo.getValueAt(fila, 0).toString());
            factory = RowSetProvider.newFactory();
            rowSet = factory.createCachedRowSet();

            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String mysqlUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=Desconectado";
            rowSet.setUrl(mysqlUrl);
            rowSet.setUsername("sa");
            rowSet.setPassword("Emi7337175.");
            rowSet.setCommand("select * from vehiculos");
            rowSet.execute();

            rowSet.setCommand("SELECT id, placas, modelo, marca, nserie, cve FROM vehiculos WHERE id=?");
            rowSet.setInt(1, id);
            rowSet.execute();

            while (rowSet.next()) {
                jTFID.setText(String.valueOf(id));
                jTFPlacas.setText(rowSet.getString("placas"));
                jTFModelo.setText(rowSet.getString("modelo"));
                jTFMarca.setText(rowSet.getString("marca"));
                jTFSerie.setText(rowSet.getString("nserie"));
                jTFCve.setText(rowSet.getString("cve"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jTableVehiculoMouseClicked

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        int id = Integer.parseInt(jTFID.getText());
        String placas = jTFPlacas.getText();
        String modelo = jTFModelo.getText();
        String marca = jTFMarca.getText();
        String nserie = jTFSerie.getText();
        int cve = Integer.parseInt(jTFCve.getText());

        try {
            factory = RowSetProvider.newFactory();
            rowSet = factory.createCachedRowSet();

            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String mysqlUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=Desconectado";
            rowSet.setUrl(mysqlUrl);
            rowSet.setUsername("sa");
            rowSet.setPassword("Emi7337175.");
            rowSet.setCommand("select * from vehiculos");
            rowSet.execute();

            rowSet.setCommand("INSERT INTO vehiculos (placas, modelo, marca, nserie, cve) VALUES (?,?,?,?,?)");
            rowSet.setString(1, placas);
            rowSet.setString(2, modelo);
            rowSet.setString(3, marca);
            rowSet.setString(4, nserie);
            rowSet.setInt(5, cve);

            if (jCBMostrar.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Porfavor coloque la clave de seguridad!.");
            } else {
                rowSet.execute();
                rowSet.next();
                JOptionPane.showMessageDialog(null, "Registro GUARDADO");
            }

            limpiar();
            cargarTabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int id = Integer.parseInt(jTFID.getText());
        String placas = jTFPlacas.getText();
        String modelo = jTFModelo.getText();
        String marca = jTFMarca.getText();
        String nserie = jTFSerie.getText();
        int cve = Integer.parseInt(jTFCve.getText());

        try {
            factory = RowSetProvider.newFactory();
            rowSet = factory.createCachedRowSet();

            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String mysqlUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=Desconectado";
            rowSet.setUrl(mysqlUrl);
            rowSet.setUsername("sa");
            rowSet.setPassword("Emi7337175.");
            rowSet.setCommand("select * from vehiculos");
            rowSet.execute();

            rowSet.setCommand("UPDATE vehiculos SET placas=?, modelo=?, marca=?, nserie=?, cve=? WHERE id=?");
            rowSet.setString(1, placas);
            rowSet.setString(2, modelo);
            rowSet.setString(3, marca);
            rowSet.setString(4, nserie);
            rowSet.setInt(5, cve);
            rowSet.setInt(6, id);
            
            if (jCBMostrar.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Porfavor coloque la clave de seguridad!.");
            } else {
                rowSet.execute();
                rowSet.next();
                JOptionPane.showMessageDialog(null, "Registro MODIFICADO");
            }

            limpiar();
            cargarTabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int id = Integer.parseInt(jTFID.getText());

        try {
            factory = RowSetProvider.newFactory();
            rowSet = factory.createCachedRowSet();

            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String mysqlUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=Desconectado";
            rowSet.setUrl(mysqlUrl);
            rowSet.setUsername("sa");
            rowSet.setPassword("Emi7337175.");
            rowSet.setCommand("select * from vehiculos");
            rowSet.execute();

            rowSet.setCommand("DELETE FROM vehiculos WHERE id=?");
            rowSet.setInt(1, id);
            
                        if (jCBMostrar.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Porfavor coloque la clave de seguridad!.");
            } else {
                rowSet.execute();
                rowSet.next();
                JOptionPane.showMessageDialog(null, "Registro BORRADOO");
            }
                        
            limpiar();
            cargarTabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void limpiar() {
        jTFPlacas.setText("");
        jTFModelo.setText("");
        jTFMarca.setText("");
        jTFSerie.setText("");
        jTFCve.setText("");
    }

    private void cargarTabla() throws SQLException {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableVehiculo.getModel();
        modeloTabla.setRowCount(0);

        factory = RowSetProvider.newFactory();
        rowSet = factory.createCachedRowSet();

        DriverManager.registerDriver(new com.mysql.jdbc.Driver());
        String mysqlUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=Desconectado";
        rowSet.setUrl(mysqlUrl);
        rowSet.setUsername("sa");
        rowSet.setPassword("Emi7337175.");
        rowSet.setCommand("select * from vehiculos");
        rowSet.execute();

        ResultSetMetaData rsmd;
        int columnas;

        try {

            rsmd = rowSet.getMetaData();
            columnas = rsmd.getColumnCount();

            while (rowSet.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rowSet.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistroAutos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegistroAutos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JCheckBox jCBMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFContraseña;
    private javax.swing.JTextField jTFCve;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFPlacas;
    private javax.swing.JTextField jTFSerie;
    private javax.swing.JTable jTableVehiculo;
    private javax.swing.JTextField jTextFieldNOMBRE;
    // End of variables declaration//GEN-END:variables
}
